name: Update Scheduler and Stop RDS

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 3 * * 0" 

jobs:
  update-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download schedule artifact
        uses: actions/download-artifact@v3
        with:
          name: schedule-file

      - name: Read calculated schedule from file
        id: read_schedule
        run: |
          NEXT_SCHEDULE=$(cat schedule.txt)
          echo "New schedule: $NEXT_SCHEDULE"
          
      - name: Update workflow file with new schedule
        run: |
          # Use the GitHub API to modify the schedule in the workflow file
          NEW_CRON=$(echo "$NEXT_SCHEDULE" | sed 's/\*/\\*/g')  # Escape the asterisks for API
          sed -i "s/cron: .*/cron: $NEW_CRON/" .github/workflows/your_workflow.yml
          
          
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .github/workflows/your_workflow.yml
          git commit -m "Update schedule for workflow"
          git push 
  # stop-rds:
  #   needs: update-cron-job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
  #         aws-region: us-east-1  

  #     - name: Stop RDS Instance
  #       run: |
  #         aws rds stop-db-instance --db-instance-identifier database-1
